# -*- coding: utf-8 -*-
"""co2_emissions_in_US.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZOP3KkJZ_B9Ot1dDMMY0GdVq-UwzwQ4O
"""

import pandas as pd

# Load data
df = pd.read_csv("co2_emissions_kt_by_country.csv")

# Preview data
df.head()

# Informasi dataset
df.info()

# Missing values
df.isnull().sum()

# duplication check
df.duplicated().sum()

#negative value check
df[df["value"]<0]

#2.
zero_emission_countries = (
    df
    .groupby('country_name')['value']
    .apply(lambda x: (x == 0).all())
    .reset_index(name='all_zero')
)

zero_emission_countries = zero_emission_countries[
    zero_emission_countries['all_zero']
]

zero_emission_countries

#3 country name standarisation
df["country_name"] = df["country_name"].replace({
 "United States of America": "United States",
 "USA": "United States",
 "UK" : "United Kingdom",
 "Russian Federation": "Russia"
})

#3. Eliminating countries with continuous zero emissions
 #number of years per country

year_count = (
    df.groupby('country_name')['year']
      .nunique()
      .reset_index(name='year_count')
)

 #country less than five years
countries_less_than_5_years = year_count[
    year_count['year_count'] < 5
]['country_name']

  #clean dataset
df_clean = df[~df['country_name'].isin(countries_less_than_5_years)]

#4, increase of co2 emission percentage

import numpy as np

df['emission_category'] = np.where(
    df['value'] < 50000, 'low',
    np.where(
        df['value'] <= 300000, 'Medium', 'High'
    )
)

df['emission_category'].value_counts()

#4. total emission per year
total_emissions_per_year = (
    df.groupby('year')['value']
      .sum()
      .reset_index(name='total_emissions')
)

total_emissions_per_year.head()

#5, co2 emission analysis
avg_emissions_per_year = (
    df.groupby('year')['value']
      .mean()
      .reset_index(name='avg_emission_kt')
)

avg_emissions_per_year.head()

#6, comparing co2 emission time to time
import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv('co2_emissions_kt_by_country.csv')

# two countries filter indonesia and usa
countries = ['Indonesia', 'United States']
df_trend = df[df['country_name'].isin(countries)]

# data sorted
df_trend = df_trend.sort_values(['country_name', 'year'])

plt.figure(figsize=(10, 5))

for country in countries:
    country_data = df_trend[df_trend['country_name'] == country]
    plt.plot(
        country_data['year'],
        country_data['value'],
        label=country
    )

plt.title('CO₂ Emission Trends Over Time')
plt.xlabel('Year')
plt.ylabel('Emission CO₂ (kt)')
plt.legend()
plt.grid(True)
plt.show()

"""CO₂ emission trends in Indonesia and the United States reveal distinct patterns shaped by their levels of economic development. In Indonesia, a developing country, emissions have generally increased over time. This growth is driven by rising energy consumption, industrialization, population growth, and continued reliance on fossil fuels, particularly coal. A temporary decline occurred around 2020, largely due to the COVID-19 pandemic, which disrupted industrial activity, transportation, and the overall economy. Following this period, emissions began to rise again as economic activity resumed.

In contrast, the United States, a developed country, exhibits a long-term pattern of stagnation and gradual decline in emissions. Early peaks were followed by reductions influenced by energy transitions from coal to natural gas and renewables, improved energy efficiency, stricter environmental regulations, and a shift from manufacturing to the service sector. Significant drops in emissions were observed during the 2008–2009 global financial crisis and in 2020 due to the pandemic. Unlike Indonesia, U.S. emissions did not return to previous peak levels, reflecting structural changes in the economy.

Overall, these trends indicate that developing countries often experience rising emissions alongside economic growth, whereas developed countries can achieve economic growth while reducing emissions through policy interventions and technological improvements. Global crises, such as the COVID-19 pandemic, have caused temporary declines in emissions across both contexts, but long-term trends are largely shaped by each country’s stage of development and energy strategy.
"""

#7, outlier anomali
import pandas as pd

# Load data
df = pd.read_csv('co2_emissions_kt_by_country.csv')

# Pastikan kolom value numerik
df['value'] = pd.to_numeric(df['value'], errors='coerce')

# Hapus nilai NaN
df = df.dropna(subset=['value'])


# DETEKSI OUTLIER (IQR)
Q1 = df['value'].quantile(0.25)
Q3 = df['value'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Ambil data outlier
outliers = df[
    (df['value'] < lower_bound) |
    (df['value'] > upper_bound)
]

# Ambil satu outlier terbesar
if not outliers.empty:
    top_outlier = outliers.sort_values(by='value', ascending=False).iloc[0]
else:
    top_outlier = None

# Tandai outlier
df['is_outlier'] = (
    (df['value'] < lower_bound) |
    (df['value'] > upper_bound)
)

top_outlier

df.head()
df.dtypes
df['value'].isna().sum()